name: Build Aab and Sign
on: workflow_dispatch
jobs:
  build:
    name: Build AAb
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    
    - name: Running bundleRelease
      run: gradle bundleRelease
    
    - name: Running JarSigner
      run: jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore app/test.keystore -storepass key01 -keypass key02 app/build/outputs/bundle/release/app-release.aab alias

    - name: Uploading Apk and Files
      uses: actions/upload-artifact@v2
      with:
        name: Aab Bundle
        path: |
            app/build/outputs/bundle
            app/build/generated
      
    
